### ISSUE TITLE
Create a proper readme.md

### ISSUE THREAD

**Issue by Gimbardo** [Gimbardo/Museye#6]

**Comment by Steffo99** [comment]
yes pls i'd like to know what this is

**Comment by Gimbardo** [comment]
@Steffo99 gotcha

**Comment by Steffo99** [comment]
dank

**Comment by Steffo99** [comment]
è un'opera d'arte

**Comment by Gimbardo** [comment]
( non funziona ancora correttamente, e si rompe molto facilmente. Appena ho voglia fixo )
